---
- hosts: all
  gather_facts: false

  vars:
    GIT_REPO: /tmp/ansible-automation/astraea
    ZK_IMAGE_NAME: ghcr.io/skiptests/astraea/zookeeper:3.7.0
    KAFKA_IMAGE_NAME: ghcr.io/skiptests/astraea/broker:2.8.1
    RANDOM_PORTS: "{{ range(10000, 30000) | shuffle(seed='0xCAFEBABE') }}"
    ZK_PORT: "{{ RANDOM_PORTS[0] }}"
    BROKER_PORT: "{{ RANDOM_PORTS[1] }}"
    EXPORTER_PORT: "{{ RANDOM_PORTS[2] }}"
    TARGET_GROUP: hosts

  pre_tasks:
    - name: Install python docker library on remote
      ansible.builtin.pip:
        name: "docker==4.1.0"

  tasks:
    - name: Clone Astraea Project
      ansible.builtin.git:
        repo: 'https://github.com/skiptests/astraea.git'
        dest: "{{ GIT_REPO }}"
        update: no

    # Launch servers
    - name: Remove old instances if necessary 
      import_tasks: tasks/remove-cluster.yml

    - name: Launch Zookeeper on specific hosts (execute script)
      ansible.builtin.command: "{{ GIT_REPO }}/docker/start_zookeeper.sh"
      environment:
        ZOOKEEPER_PORT: "{{ ZK_PORT }}"
      register: output_zookeeper_script
      when: inventory_hostname == groups[TARGET_GROUP][0]

    - name: Launch Apache Kafka on all hosts (execute script)
      ansible.builtin.command: "{{ GIT_REPO }}/docker/start_broker.sh zookeeper.connect={{ groups[TARGET_GROUP][0] }}:{{ ZK_PORT }}"
      environment:
        BROKER_PORT: "{{ BROKER_PORT }}"
        EXPORTER_PORT: "{{ EXPORTER_PORT }}"

    # Generate useful cluster stat
    - name: Generate cluster summary
      ansible.builtin.template:
        src: ./templates/summary.j2
        dest: /tmp/cluster-summary
