- name: Install python & pip on remote
  ansible.builtin.package:
    name:
      - python3
      - pip
      - acl
      - iperf
    state: present
  become: true

- ansible.builtin.package:
    name:
      - python-is-python3
    state: present
  become: true

- name: install python packages
  ansible.builtin.pip:
    name: 
      - "requests"
      - "setuptools"
      - "docker==4.1.0"
