- name: Install python & pip on remote
  ansible.builtin.package:
    name:
      - python3
      - openjdk-11-jre-headless
      - openjdk-17-jre-headless
      - pip
      - acl
      - iperf
      - fio
      - tuned
    state: present
  become: true

- name: set java 17
  ansible.builtin.command: "update-java-alternatives --set /usr/lib/jvm/java-1.17.0-openjdk-amd64"
  become: true

- ansible.builtin.package:
    name:
      - python-is-python3
    state: present
  become: true

- name: install python packages
  ansible.builtin.pip:
    name: 
      - "requests"
      - "setuptools"
      - "docker==4.1.0"

- name: write tuned mode
  ansible.builtin.copy:
    content: |
      throughput-performance
    dest: /etc/tuned/active_profile

- name: write tuned mode
  ansible.builtin.copy:
    content: |
      manual
    dest: /etc/tuned/profile_mode

- name: restart tuned
  ansible.builtin.systemd:
    name: tuned
    state: restarted
