---
- name: Stop Performance
  import_playbook: ./backbone-imbalance-stop.yml

- hosts: backbone_imbalance_hosts
  gather_facts: true

  vars_files:
    - ../../common-variables.yml
    - ../../common-configs.yml

  vars:
    BROKER_GROUP: cluster_hosts
    JMX_CONFIG_FILE: "/tmp/performance-jmx-exporter.yml"

  tasks:
    - name: set fact, generate the bootstrap server address list
      ansible.builtin.set_fact:
        bootstrap_servers: "{{ groups[BROKER_GROUP] | product([BROKER_PORT]) | map('join', ':') | join(',') }}" 
        throttle_config: "--throttle {{ throttle }}"
        throughput_config: "--throughput {{ throughput }}"

    - name: prepare JMX exporter config file
      ansible.builtin.template:
        src: ../../templates/performance-jmx-exporter.yml
        dest: "{{ JMX_CONFIG_FILE }}"

    - name: Launch Performance Tool
      community.docker.docker_container:
        name: performance-jmx-exporter
        image: bitnami/jmx-exporter:0.18.0
        state: started
        ports:
          - "5567:5567"
        mounts:
          - source: "{{ JMX_CONFIG_FILE }}" 
            target: "{{ JMX_CONFIG_FILE }}"
            type: bind
            read_only: true
        command:
          - "5567"
          - "{{ JMX_CONFIG_FILE }}"

    - name: Launch Performance Tool
      community.docker.docker_container:
        name: performance
          # image: ghcr.io/garyparrot/astraea/app:consumer-first-yes
        image: ghcr.io/skiptests/astraea/app:main
        state: started
        recreate: yes
        env:
          JAVA_TOOL_OPTIONS: |
            -Dcom.sun.management.jmxremote 
            -Dcom.sun.management.jmxremote.authenticate=false 
            -Dcom.sun.management.jmxremote.ssl=false
            -Dcom.sun.management.jmxremote.port=6655
            -Dcom.sun.management.jmxremote.rmi.port=6655
            -Djava.rmi.server.hostname={{ ansible_host }}
          JAVA_OPTS: -Xmx16g
        ports:
          - "6655:6655"
        command:
          - "./bin/app"
          - "performance"
          - "--bootstrap.servers {{ bootstrap_servers }}"
          - "--run.until 6h"
          - "--topics {{ topics }}"
          - "{{ throttle_config if throttle_enable else '' }}"
          - "{{ throughput_config if throughput_enable else '' }}"
          - "--record.key.table.seed {{ key_table_seed }}"
          - "--key.distribution {{ key_distribution }}"
          - "--key.distribution.config '{{ key_distribution_config | default('k=v') }}'"
          - "--producers 4"
          - "--consumers 0"
          - "--value.size 10KiB" 
          - "--configs receive.buffer.bytes=402400,max.partition.fetch.bytes=10485760,fetch.max.wait.ms=0,check.crcs=false,acks=0,metrics.sample.window.ms=100"

    - name: Launch Consumer
      community.docker.docker_container:
        name: consumer
        image: ghcr.io/garyparrot/astraea/app:dedicated_consumer
        state: started
        recreate: yes
        env:
          JAVA_TOOL_OPTIONS: |
            -Dcom.sun.management.jmxremote 
            -Dcom.sun.management.jmxremote.authenticate=false 
            -Dcom.sun.management.jmxremote.ssl=false
            -Dcom.sun.management.jmxremote.port=5566
            -Dcom.sun.management.jmxremote.rmi.port=5566
            -Djava.rmi.server.hostname={{ ansible_host }}
          JAVA_OPTS: -Xmx16g
        ports:
          - "5566:5566"
        command:
          - "./bin/app"
          - "consumer"
          - "{{ bootstrap_servers }}"
          - "backbone"
