---
- hosts: backbone_imbalance_hosts
  gather_facts: false
  strategy: free

  vars_files:
    - ../../common-variables.yml

  tasks:

    - name: Search for loading
      ansible.builtin.command: "docker ps -aq --filter name=performance"
      register: any_worker
      when: inventory_hostname in groups["backbone_imbalance_hosts"]

    - name: stop exporter
      community.docker.docker_container:
        name: performance-jmx-exporter
        image: bitnami/jmx-exporter:0.18.0
        state: absent

    - name: stop worker
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ any_worker.stdout_lines }}"
      changed_when: any_worker.stdout_lines | length > 0 | bool
      when: inventory_hostname in groups["backbone_imbalance_hosts"]

    - name: Search for loading
      ansible.builtin.command: "docker ps -aq --filter name=consumer"
      register: any_worker
      when: inventory_hostname in groups["backbone_imbalance_hosts"]

    - name: stop worker
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ any_worker.stdout_lines }}"
      changed_when: any_worker.stdout_lines | length > 0 | bool
      when: inventory_hostname in groups["backbone_imbalance_hosts"]
