---
- name: Stop Performance
  import_playbook: ./backbone-imbalance-stop.yml

- hosts: backbone_imbalance_hosts
  gather_facts: true

  vars_files:
    - ../../common-variables.yml
    - ../../common-configs.yml

  vars:
    BROKER_GROUP: cluster_hosts
    JMX_CONFIG_FILE: "/tmp/performance-jmx-exporter.yml"

  tasks:
    - name: set fact, generate the bootstrap server address list
      ansible.builtin.set_fact:
        bootstrap_servers: "{{ groups[BROKER_GROUP] | product([BROKER_PORT]) | map('join', ':') | join(',') }}" 
        throttle_config: "--throttle {{ throttle }}"
        throughput_config: "--throughput {{ throughput }}"

    - name: prepare JMX exporter config file
      ansible.builtin.template:
        src: ../../templates/performance-jmx-exporter.yml
        dest: "{{ JMX_CONFIG_FILE }}"

    - name: Launch Performance Tool
      community.docker.docker_container:
        name: performance-jmx-exporter
        image: bitnami/jmx-exporter:0.18.0
        state: started
        recreate: yes
        ports:
          - "5567:5567"
        mounts:
          - source: "{{ JMX_CONFIG_FILE }}" 
            target: "{{ JMX_CONFIG_FILE }}"
            type: bind
            read_only: true
        command:
          - "5567"
          - "{{ JMX_CONFIG_FILE }}"

    - name: Launch Performance Tool
      community.docker.docker_container:
        name: performance
        image: ghcr.io/skiptests/astraea/app:main
        state: started
        recreate: yes
        env:
          JAVA_TOOL_OPTIONS: |
            -Dcom.sun.management.jmxremote 
            -Dcom.sun.management.jmxremote.authenticate=false 
            -Dcom.sun.management.jmxremote.ssl=false
            -Dcom.sun.management.jmxremote.port=5566
            -Dcom.sun.management.jmxremote.rmi.port=5566
            -Djava.rmi.server.hostname={{ ansible_host }}
          JAVA_OPTS: -Xmx16g
        ports:
          - "5566:5566"
        command:
          - "./bin/app"
          - "performance"
          - "--bootstrap.servers {{ bootstrap_servers }}"
          - "--run.until 3m"
          - "--topics {{ topics }}"
          - "{{ throttle_config if throttle_enable else '' }}"
          - "{{ throughput_config if throughput_enable else '' }}"
          - "--record.key.table.seed {{ key_table_seed }}"
          - "--key.distribution {{ key_distribution }}"
          - "--key.distribution.config '{{ key_distribution_config | default('k=v') }}'"
          - "--producers 2"
          - "--consumers 1"
          # - "--group.id theGroup"
          - "--configs buffer.memory=50000000,linger.ms=5,batch.size=50000,max.request.size=10485760,send.buffer.bytes=1002400,receive.buffer.bytes=10024000,max.partition.fetch.bytes=3000000,fetch.max.wait.ms=0,check.crcs=false,acks=0,metrics.sample.window.ms=100"
          - "--value.size 10KiB" 
              # - "--configs send.buffer.bytes=402400,receive.buffer.bytes=402400,max.partition.fetch.bytes=10485760,fetch.max.wait.ms=0,check.crcs=false,acks=0,metrics.sample.window.ms=100"
