global:
  scrape_interval: 2s
  external_labels:
    monitor: 'prometheus'
scrape_configs:
  - job_name: 'kafka'
    scrape_interval: 2s
    scrape_timeout: 2s
    static_configs:
      - targets:
        {% for host in groups[KAFKA_GROUP] %}
        - {{ host }}:{{ EXPORTER_PORT }}
        {% endfor %}

  - job_name: 'node'
    scrape_interval: 1s
    scrape_timeout: 1s
    static_configs:
      - targets:
        {% for host in groups[TARGET_GROUP] %}
        - {{ host }}:{{ NODE_EXPORTER_PORT }}
        {% endfor %}

  - job_name: 'performance-tool'
    scrape_interval: 2s
    scrape_timeout: 2s
    static_configs:
      - targets:
        - 192.168.103.183:5567
        - 192.168.103.184:5567
        - 192.168.103.141:5567
        - 192.168.103.142:5567
        - 192.168.103.143:5567
        - 192.168.103.144:5567
        - 192.168.103.145:5567
        - 192.168.103.146:5567
        - 192.168.103.147:5567
