---
- hosts: all
  gather_facts: false

  vars:
    GIT_REPO: https://github.com/garyparrot/astraea.git
    GIT_REPO_BRANCH: temp-fix
    GIT_REPO_DEST: /tmp/ansible-automation/astraea
    ZK_IMAGE_NAME: ghcr.io/skiptests/astraea/zookeeper:3.7.0
    KAFKA_SCRIPT: "{{ GIT_REPO_DEST }}/docker/start_broker.sh"
    KAFKA_IMAGE_NAME: ghcr.io/skiptests/astraea/broker:2.8.1
    RANDOM_PORTS: "{{ range(10000, 30000) | shuffle(seed='0xCAFEBABE'+ KAFKA_SCRIPT) }}"
    ZK_PORT: "{{ RANDOM_PORTS[0] }}"
    BROKER_PORT: "{{ RANDOM_PORTS[1] }}"
    EXPORTER_PORT: "{{ RANDOM_PORTS[2] }}"
    JMX_PORT: "{{ RANDOM_PORTS[3] }}"
    TARGET_GROUP: hosts
    DO_PACKAGE_INSTALL: "{{ INSTALL_PACKAGES | default(false) }}"
    BASIC_KAFKA_ARGS:
      - "{{ KAFKA_SCRIPT }}"
      - "zookeeper.connect={{ groups[TARGET_GROUP][0] }}:{{ ZK_PORT }}"


  pre_tasks:
    - name: Install python & pip on remote
      ansible.builtin.package:
        name:
          - python
          - pip
        state: present
      when: DO_PACKAGE_INSTALL
    - name: Install python docker library on remote
      ansible.builtin.pip:
        name: "docker==4.1.0"
      when: DO_PACKAGE_INSTALL

  tasks:
    - name: Clone Astraea Project
      ansible.builtin.git:
        repo: "{{ GIT_REPO }}"
        dest: "{{ GIT_REPO_DEST }}"
        update: yes
        version: "{{ GIT_REPO_BRANCH }}"

    # Launch servers
    - name: Remove old instances if necessary 
      import_tasks: ../tasks/remove-cluster.yml

    - name: Launch Zookeeper on specific host (execute script)
      ansible.builtin.command: "{{ GIT_REPO_DEST }}/docker/start_zookeeper.sh"
      environment:
        ZOOKEEPER_PORT: "{{ ZK_PORT }}"
      register: output_zookeeper_script
      when: inventory_hostname == groups[TARGET_GROUP][0]

    - name: Launch Apache Kafka on all hosts (execute script)
      ansible.builtin.command: 
        argv: "{{ BASIC_KAFKA_ARGS + EXTEND_KAFKA_ARGS }}"
      environment:
        BROKER_PORT: "{{ BROKER_PORT }}"
        EXPORTER_PORT: "{{ EXPORTER_PORT }}"
        JMX_PORT: "{{ JMX_PORT }}"
      register: kafka_script_output

    - name: debug kafka_script_output
      ansible.builtin.debug:
        var: kafka_script_output


    # Generate useful cluster stat
    - name: Generate cluster summary
      ansible.builtin.template:
        src: ../templates/summary.j2
        dest: /tmp/cluster-summary
