---
- hosts: hosts
  gather_facts: false

  vars_files:
    - ../common-variables.yml

- name: Import playbook
  ansible.builtin.import_playbook: ./apache-kafka-cluster.yml
  vars:
    KAFKA_SCRIPT: "{{ GIT_REPO_DEST }}/docker/start_confluent_broker.sh"
    KAFKA_IMAGE_NAME: confluentinc/cp-enterprise-kafka:latest
