- hosts: cluster_hosts

  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.docker

  tasks:
    - name: add user to docker group
      ansible.builtin.user: 
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
