---
- hosts: loading-producer
  gather_facts: false
  strategy: free

  # vars_prompt:
  #   - name: benchmark_name
  #     prompt: Name this benchmark (this name will be prefix to every created topic)
  #     private: no

  vars_files:
    - ../common-variables.yml

  vars:
    BROKER_GROUP: cluster_hosts

  tasks:

    - name: set fact, generate the bootstrap server address list
      ansible.builtin.set_fact:
        bootstrap_servers: "{{ groups[BROKER_GROUP] | product([BROKER_PORT]) | map('join', ':') | join(',') }}" 

    - name: debug topic name
      ansible.builtin.debug:
        msg:
          - "topic_name: {{ topic_name }}"
          - "throttle: {{ throttle }}"
    
    - name: launch the worker
      community.docker.docker_container:
        name: "{{ inventory_hostname }}"
        image: app:0.0.1-SNAPSHOT
        state: started
        recreate: yes
        command: 
          - producer
          - "--bootstrap.servers {{ bootstrap_servers }}"
          - "--batch.size {{ batchSize | default('900KiB') }}"
          - "--record.size {{ recordSize | default('100KiB') }}"
          - "--max.in.flight {{ inflight | default('30') }}"
          - "--buffer.memory {{ bufferMemory | default('30MiB') }}"
          - "--load.fraction {{ load_map }}"
          - "--producers {{ producers | default('-1') }}"
          - "--send.limit 3000000"
          - "--linger.ms 3000"
          - "--max.producer 50MiB"
        # - "--topic {{ topic_name }}"
        # - "--throttle {{ throttle }}"
