---
- hosts: payload_hosts
  gather_facts: true

  # vars_prompt:
  #   - name: benchmark_name
  #     prompt: Name this benchmark (this name will be prefix to every created topic)
  #     private: no

  vars_files:
    - ../common-variables.yml

  vars:
    BROKER_GROUP: cluster_hosts

  tasks:
    - name: clone astraea project
      ansible.builtin.git:
        repo: "{{ GIT_REPO }}"
        dest: "{{ GIT_REPO_BASE_DEST }}/{{ inventory_hostname }}"
        update: yes
        version: "{{ GIT_REPO_BRANCH }}"

    - name: set fact, generate the bootstrap server address list
      ansible.builtin.set_fact:
        bootstrap_servers: "{{ groups[BROKER_GROUP] | product([BROKER_PORT]) | map('join', ':') | join(',') }}" 

    - name: debug topic name
      ansible.builtin.debug:
        msg:
          - "topic_name: {{ topic_name }}"
          - "partitions: {{ partitions }}"
          - "replicas  : {{ replicas }}"
          - "throughput: {{ throughput }}"
    
    - name: launch the worker
      community.docker.docker_container:
        name: "{{ inventory_hostname }}"
        image: ghcr.io/skiptests/astraea/app:main
        state: started
        recreate: yes
        command: 
          - /opt/astraea/bin/app
          - performance
          - "--bootstrap.servers {{ bootstrap_servers }}"
          - "--producers 2"
          - "--consumers 4"
          - "--record.size 10KiB"
          - "--topic {{ topic_name }}"
          - "--partitions {{ partitions }}"
          - "--replicas {{ replicas }}"
          - "--run.until 256h"
          - "--throughput {{ throughput }}"
