---
- hosts: all
  gather_facts: false

  vars_files:
    - ../common-variables.yml

  vars:
    TARGET_GROUP: "hosts"

  tasks:
    - name: Clone Astraea Project
      ansible.builtin.git:
        repo: "{{ GIT_REPO }}"
        dest: "{{ GIT_REPO_DEST }}"
        update: yes
        version: "{{ GIT_REPO_BRANCH }}"

    - name: stop old node exporter
      ansible.builtin.import_tasks: ../tasks/remove-monitoring-tools.yml
      
    - name: Launch Node Exporter on all host
      ansible.builtin.command:
        argv:
          - "{{ NODE_EXPORTER_SCRIPT }}"
      environment:
        PORT: "{{ NODE_EXPORTER_PORT }}"
      when: inventory_hostname in groups.hosts

    - name: Launch Prometheus on first host
      ansible.builtin.command:
        argv:
          - "{{ PROMETHEUS_SCRIPT }}"
          - "start"
      environment:
        PROMETHEUS_PORT: "{{ PROMETHEUS_PORT }}"
      when: inventory_hostname == groups[TARGET_GROUP][0]

    - name: Refresh prometheus on first host
      ansible.builtin.command:
        argv:
          - "{{ PROMETHEUS_SCRIPT }}"
          - "refresh"
          - "{{ groups[TARGET_GROUP] | product([EXPORTER_PORT]) | map('join', ':') | join(',') }}"
          - "{{ groups[TARGET_GROUP] | product([NODE_EXPORTER_PORT]) | map('join', ':') | join(',') }}"
      environment:
        PROMETHEUS_PORT: "{{ PROMETHEUS_PORT }}"
        scrape_interval: "3000ms"
        scrape_timeout: "3000ms"
      when: inventory_hostname == groups[TARGET_GROUP][0]

    - name: Launch Grafana on localhost
      ansible.builtin.command:
        argv:
          - "{{ GRAFANA_SCRIPT }}"
          - "start"
      when: inventory_hostname in groups.local

    - name: Setup prometheus source for local Grafana 
      ansible.builtin.command:
          "{{ GRAFANA_SCRIPT }} add_prom_source admin:admin prometheus http://{{ groups[TARGET_GROUP][0] }}:{{ PROMETHEUS_PORT }}/"
      when: inventory_hostname in groups.local

    - name: debug
      ansible.builtin.debug:
        msg:
            - "Exporter Port: {{ EXPORTER_PORT }}"
            - "Bootstrap servers: {{ groups[TARGET_GROUP] | product([BROKER_PORT]) | map('join', ':') | join(',') }}"
            - "Prometheus : http://{{ groups[TARGET_GROUP][0] }}:{{ PROMETHEUS_PORT }}/"
            - "Grafana : http://localhost:3000/"
      when: inventory_hostname in groups.local
