---
- hosts:
    - monitoring
    - local
  gather_facts: true

  vars_files:
    - ../common-variables.yml

  vars:
    KAFKA_GROUP: "cluster_hosts"
    TARGET_GROUP: "monitoring"
    CONFIG_PATH: "{{ GIT_REPO_BASE_DEST }}/prometheus.yml"

  tasks:
    - name: clone astraea project and move to the newest commit
      ansible.builtin.git:
        repo: "{{ GIT_REPO }}"
        dest: "{{ GIT_REPO_DEST }}"
        update: yes
        version: "{{ GIT_REPO_BRANCH }}"

    - name: prepare one for the main astraea
      ansible.builtin.git:
        repo: "https://github.com/skiptests/astraea.git"
        dest: "{{ GIT_REPO_MAIN_DEST }}"
        update: yes
        force: yes

    - name: stop old node exporters
      ansible.builtin.import_tasks: ../tasks/remove-monitoring-tools.yml
      
    - name: launch node exporter on all hosts
      ansible.builtin.command:
        argv:
          - "{{ NODE_EXPORTER_SCRIPT }}"
      environment:
        PORT: "{{ NODE_EXPORTER_PORT }}"
      when: inventory_hostname in groups[TARGET_GROUP]

    - name: template the Prometheus config file
      ansible.builtin.template:
        src: ../templates/prometheus.yml
        dest: "{{ CONFIG_PATH }}"

    - name: launch Prometheus on the first host
      community.docker.docker_container:
        name: "prometheus-{{ PROMETHEUS_PORT }}"
        image: prom/prometheus:v2.32.1
        state: started
        recreate: true
        command:
          - "--config.file=/etc/prometheus/prometheus.yml" 
          - "--storage.tsdb.path=/prometheus" 
          - "--web.console.libraries=/usr/share/prometheus/console_libraries"
          - "--web.console.templates=/usr/share/prometheus/consoles"
          - "--storage.tsdb.retention.time=7d"
        published_ports:
          - "{{ PROMETHEUS_PORT }}:9090"
        volumes:
          - "{{ CONFIG_PATH }}:/etc/prometheus/prometheus.yml"
        mounts:
          - type: volume
            source: "1187b8fc047ee320ebde96e06b12717e6c981716a5066ed1ec89ba40d499eab9"
            target: "/prometheus"

      environment:
        PROMETHEUS_PORT: "{{ PROMETHEUS_PORT }}"
      when: inventory_hostname == groups[TARGET_GROUP][0]

    - name: test if cluster is on 
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}" 
        port: 3000
        timeout: 5
        msg: "wait Grafana up timeout"
      when: inventory_hostname in groups["local"]
      ignore_errors: yes

    - name: setup Prometheus data source for the local Grafana
      ansible.builtin.command:
          "{{ GRAFANA_SCRIPT }} add_prom_source admin:admin prometheus http://{{ groups[TARGET_GROUP][0] }}:{{ PROMETHEUS_PORT }}/"
      when: inventory_hostname in groups["local"]

- name: import the friendly print-info playbook
  import_playbook: ./print-info.yml
