---
- hosts:
    - cluster_hosts
    - local
  gather_facts: true

  vars_files:
    - ../common-variables.yml

  vars:
    TARGET_GROUP: cluster_hosts

  tasks:
    - name: prepare balancer.properties
      ansible.builtin.template:
        src: ../templates/balancer.properties.j2
        dest: "{{ BALANCER_CONFIG_FILE }}"

    - name: test if cluster is on 
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}" 
        port: "{{ BROKER_PORT }}"
        timeout: 3
        msg: "Kafka broker {{ ansible_host }}:{{ BROKER_PORT }} is unreachable."
      when: inventory_hostname in groups[TARGET_GROUP]
      ignore_errors: yes
      register: test_kafka

    - name: test if prometheus is on 
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}" 
        port: "{{ PROMETHEUS_PORT }}"
        timeout: 3
        msg: "No prometheus detected at {{ ansible_host }}:{{ PROMETHEUS_PORT }}"
      when: inventory_hostname == groups[TARGET_GROUP][0]
      ignore_errors: yes
      register: test_prometheus

    - name: show cluster & monitoring stack information
      ansible.builtin.debug:
        msg:
            - "ZK port: {{ ZK_PORT }}"
            - "Boostrap Servers = 
              {{ groups[TARGET_GROUP] | product([BROKER_PORT]) | map('join', ':') | join(',') }}"
            - "JMX Servers = 
              {{ groups[TARGET_GROUP] | product([JMX_PORT]) | map('join', ':') | join(',') }}"
            - "Kafka Exporters = 
              {{ groups[TARGET_GROUP] | product([EXPORTER_PORT]) | map('join', ':') | join(',') }}"
            - "Node Exporters = 
              {{ groups[TARGET_GROUP] | product([NODE_EXPORTER_PORT]) | map('join', ':') | join(',') }}"
            - "Prometheus = 
              http://{{ groups[TARGET_GROUP][0] }}:{{ PROMETHEUS_PORT }}"
            - "Grafana = http://localhost:3000/"
      when: inventory_hostname in groups.local
