---
- hosts: loading-producer-hosts
  gather_facts: false
  strategy: free

  vars_files:
    - ../common-variables.yml

  tasks:

    - name: Search for loading
      ansible.builtin.command: "docker ps -aq --filter name=loading*"
      register: any_worker
      when: inventory_hostname in groups["loading-producer-hosts"]

    - name: stop worker
      community.docker.docker_container:
        name: "{{ item }}"
        image: ghcr.io/garyparrot/astraea/app:performance-revise
        state: absent
      loop: "{{ any_worker.stdout_lines }}"
      changed_when: any_worker.stdout_lines | length > 0 | bool
      when: inventory_hostname in groups["loading-producer-hosts"]
